.class public Ljadx/core/d/a/a;
.super Ljava/lang/Object;
.source "AndroidResourcesUtils.java"


# static fields
.field private static final a:Lorg/i/b;


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .prologue
    .line 31
    const-class v0, Ljadx/core/d/a/a;

    invoke-static {v0}, Lorg/i/c;->a(Ljava/lang/Class;)Lorg/i/b;

    move-result-object v0

    sput-object v0, Ljadx/core/d/a/a;->a:Lorg/i/b;

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .prologue
    .line 33
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 34
    return-void
.end method

.method public static a(Ljadx/core/c/d/p;Ljadx/core/e/g;)Ljadx/core/c/d/b;
    .locals 6

    .prologue
    const/4 v5, 0x0

    const/4 v4, 0x1

    .line 38
    invoke-virtual {p0}, Ljadx/core/c/d/p;->e()Ljava/lang/String;

    move-result-object v2

    .line 39
    if-eqz v2, :cond_0

    new-instance v0, Ljava/lang/StringBuilder;

    invoke-static {v2}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    const-string v1, ".R"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 40
    :goto_0
    invoke-virtual {p0, v0}, Ljadx/core/c/d/p;->a(Ljava/lang/String;)Ljadx/core/c/d/b;

    move-result-object v1

    .line 41
    if-eqz v1, :cond_1

    .line 42
    invoke-static {v1, p1, v4}, Ljadx/core/d/a/a;->a(Ljadx/core/c/d/b;Ljadx/core/e/g;Z)V

    move-object v0, v1

    .line 58
    :goto_1
    return-object v0

    .line 39
    :cond_0
    const-string v0, "R"

    goto :goto_0

    .line 45
    :cond_1
    sget-object v1, Ljadx/core/d/a/a;->a:Lorg/i/b;

    const-string v3, "Can\'t find \'R\' class in app package: {}"

    invoke-interface {v1, v3, v2}, Lorg/i/b;->b(Ljava/lang/String;Ljava/lang/Object;)V

    .line 46
    const-string v1, "R"

    invoke-virtual {p0, v1}, Ljadx/core/c/d/p;->b(Ljava/lang/String;)Ljava/util/List;

    move-result-object v1

    .line 47
    invoke-interface {v1}, Ljava/util/List;->size()I

    move-result v2

    if-ne v2, v4, :cond_2

    .line 48
    invoke-interface {v1, v5}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljadx/core/c/d/b;

    .line 49
    invoke-static {v0, p1, v4}, Ljadx/core/d/a/a;->a(Ljadx/core/c/d/b;Ljadx/core/e/g;Z)V

    goto :goto_1

    .line 52
    :cond_2
    invoke-interface {v1}, Ljava/util/List;->isEmpty()Z

    move-result v2

    if-nez v2, :cond_3

    .line 53
    sget-object v2, Ljadx/core/d/a/a;->a:Lorg/i/b;

    const-string v3, "Found several \'R\' class candidates: {}"

    invoke-interface {v2, v3, v1}, Lorg/i/b;->b(Ljava/lang/String;Ljava/lang/Object;)V

    .line 55
    :cond_3
    sget-object v1, Ljadx/core/d/a/a;->a:Lorg/i/b;

    const-string v2, "App \'R\' class not found, put all resources ids to : \'{}\'"

    invoke-interface {v1, v2, v0}, Lorg/i/b;->b(Ljava/lang/String;Ljava/lang/Object;)V

    .line 56
    invoke-static {p0, v0, p1}, Ljadx/core/d/a/a;->a(Ljadx/core/c/d/p;Ljava/lang/String;Ljadx/core/e/g;)Ljadx/core/c/d/b;

    move-result-object v0

    .line 57
    invoke-static {v0, p1, v5}, Ljadx/core/d/a/a;->a(Ljadx/core/c/d/b;Ljadx/core/e/g;Z)V

    goto :goto_1
.end method

.method private static a(Ljadx/core/c/d/p;Ljava/lang/String;Ljadx/core/e/g;)Ljadx/core/c/d/b;
    .locals 4

    .prologue
    .line 74
    invoke-virtual {p0}, Ljadx/core/c/d/p;->b()Ljava/util/List;

    move-result-object v0

    .line 75
    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v1

    if-eqz v1, :cond_0

    .line 76
    const/4 v0, 0x0

    .line 81
    :goto_0
    return-object v0

    .line 78
    :cond_0
    new-instance v1, Ljadx/core/c/d/b;

    const/4 v2, 0x0

    invoke-interface {v0, v2}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljadx/core/c/d/c;

    sget-object v2, Lorg/d/b/a;->a:Lorg/d/b/a;

    invoke-virtual {v2}, Lorg/d/b/a;->a()I

    move-result v2

    sget-object v3, Lorg/d/b/a;->e:Lorg/d/b/a;

    invoke-virtual {v3}, Lorg/d/b/a;->a()I

    move-result v3

    or-int/2addr v2, v3

    invoke-direct {v1, v0, p1, v2}, Ljadx/core/c/d/b;-><init>(Ljadx/core/c/d/c;Ljava/lang/String;I)V

    .line 79
    sget-object v0, Ljadx/core/c/a/b;->f:Ljadx/core/c/a/b;

    const-string v2, "This class is generated by JADX"

    invoke-virtual {v1, v0, v2}, Ljadx/core/c/d/b;->a(Ljadx/core/c/a/b;Ljava/lang/Object;)V

    .line 80
    sget-object v0, Ljadx/core/c/d/o;->c:Ljadx/core/c/d/o;

    invoke-virtual {v1, v0}, Ljadx/core/c/d/b;->a(Ljadx/core/c/d/o;)V

    move-object v0, v1

    .line 81
    goto :goto_0
.end method

.method private static a(Ljadx/core/c/d/b;Ljadx/core/e/g;Z)V
    .locals 8

    .prologue
    .line 85
    new-instance v2, Ljava/util/TreeMap;

    invoke-direct {v2}, Ljava/util/TreeMap;-><init>()V

    .line 86
    if-eqz p2, :cond_0

    .line 87
    invoke-virtual {p0}, Ljadx/core/c/d/b;->n()Ljava/util/List;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-nez v0, :cond_2

    .line 91
    :cond_0
    invoke-virtual {p1}, Ljadx/core/e/g;->a()Ljava/util/Collection;

    move-result-object v0

    invoke-interface {v0}, Ljava/util/Collection;->iterator()Ljava/util/Iterator;

    move-result-object v3

    :cond_1
    :goto_1
    invoke-interface {v3}, Ljava/util/Iterator;->hasNext()Z

    move-result v0

    if-nez v0, :cond_3

    .line 114
    return-void

    .line 87
    :cond_2
    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljadx/core/c/d/b;

    .line 88
    invoke-virtual {v0}, Ljadx/core/c/d/b;->z()Ljava/lang/String;

    move-result-object v3

    invoke-interface {v2, v3, v0}, Ljava/util/Map;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    goto :goto_0

    .line 91
    :cond_3
    invoke-interface {v3}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Ljadx/core/e/a/d;

    .line 92
    invoke-virtual {v0}, Ljadx/core/e/a/d;->b()Ljava/lang/String;

    move-result-object v1

    new-instance v4, Ljadx/core/d/a/a$1;

    invoke-direct {v4, p0, p2}, Ljadx/core/d/a/a$1;-><init>(Ljadx/core/c/d/b;Z)V

    invoke-static {v2, v1, v4}, Ljadx/core/d/j;->a(Ljava/util/Map;Ljava/lang/Object;Ljadx/core/d/e;)Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Ljadx/core/c/d/b;

    .line 103
    invoke-virtual {v0}, Ljadx/core/e/a/d;->c()Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v1, v4}, Ljadx/core/c/d/b;->b(Ljava/lang/String;)Ljadx/core/c/d/e;

    move-result-object v4

    .line 104
    if-nez v4, :cond_1

    .line 105
    invoke-virtual {v1}, Ljadx/core/c/d/b;->t()Ljadx/core/c/d/c;

    move-result-object v4

    invoke-virtual {v1}, Ljadx/core/c/d/b;->x()Ljadx/core/c/b/b;

    move-result-object v5

    invoke-virtual {v0}, Ljadx/core/e/a/d;->c()Ljava/lang/String;

    move-result-object v6

    sget-object v7, Ljadx/core/c/c/a/a;->a:Ljadx/core/c/c/a/a;

    invoke-static {v4, v5, v6, v7}, Ljadx/core/c/b/d;->a(Ljadx/core/c/d/c;Ljadx/core/c/b/b;Ljava/lang/String;Ljadx/core/c/c/a/a;)Ljadx/core/c/b/d;

    move-result-object v4

    .line 106
    new-instance v5, Ljadx/core/c/d/e;

    sget-object v6, Lorg/d/b/a;->a:Lorg/d/b/a;

    invoke-virtual {v6}, Lorg/d/b/a;->a()I

    move-result v6

    sget-object v7, Lorg/d/b/a;->d:Lorg/d/b/a;

    invoke-virtual {v7}, Lorg/d/b/a;->a()I

    move-result v7

    or-int/2addr v6, v7

    sget-object v7, Lorg/d/b/a;->e:Lorg/d/b/a;

    invoke-virtual {v7}, Lorg/d/b/a;->a()I

    move-result v7

    or-int/2addr v6, v7

    invoke-direct {v5, v1, v4, v6}, Ljadx/core/c/d/e;-><init>(Ljadx/core/c/d/b;Ljadx/core/c/b/d;I)V

    .line 107
    invoke-virtual {v0}, Ljadx/core/e/a/d;->a()I

    move-result v0

    invoke-static {v0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    move-result-object v0

    invoke-static {v0}, Ljadx/core/c/d/a/d;->a(Ljava/lang/Object;)Ljadx/core/c/d/a/d;

    move-result-object v0

    invoke-virtual {v5, v0}, Ljadx/core/c/d/e;->a(Ljadx/core/c/a/g;)V

    .line 108
    invoke-virtual {v1}, Ljadx/core/c/d/b;->k()Ljava/util/List;

    move-result-object v0

    invoke-interface {v0, v5}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 109
    if-eqz p2, :cond_1

    .line 110
    sget-object v0, Ljadx/core/c/a/b;->f:Ljadx/core/c/a/b;

    const-string v1, "added by JADX"

    invoke-virtual {v5, v0, v1}, Ljadx/core/c/d/e;->a(Ljadx/core/c/a/b;Ljava/lang/Object;)V

    goto :goto_1
.end method

.method public static a(Ljadx/core/a/d;Ljadx/core/a/b;Ljadx/core/c/b/b;)Z
    .locals 3

    .prologue
    .line 62
    invoke-virtual {p2}, Ljadx/core/c/b/b;->j()Ljadx/core/c/b/b;

    move-result-object v0

    .line 63
    if-eqz v0, :cond_0

    invoke-virtual {v0}, Ljadx/core/c/b/b;->e()Ljava/lang/String;

    move-result-object v1

    const-string v2, "R"

    invoke-virtual {v1, v2}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    move-result v1

    if-eqz v1, :cond_0

    .line 64
    invoke-virtual {p1, p0, v0}, Ljadx/core/a/b;->a(Ljadx/core/a/d;Ljadx/core/c/b/b;)V

    .line 65
    const/16 v0, 0x2e

    invoke-virtual {p0, v0}, Ljadx/core/a/d;->b(C)Ljadx/core/a/d;

    .line 66
    invoke-virtual {p2}, Ljadx/core/c/b/b;->b()Ljadx/core/c/b/b;

    move-result-object v0

    invoke-virtual {v0}, Ljadx/core/c/b/b;->e()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {p0, v0}, Ljadx/core/a/d;->c(Ljava/lang/String;)Ljadx/core/a/d;

    .line 67
    const/4 v0, 0x1

    .line 69
    :goto_0
    return v0

    :cond_0
    const/4 v0, 0x0

    goto :goto_0
.end method
