.class public final Lcom/uc/ark/sdk/components/a/i;
.super Ljava/lang/Object;
.source "ProGuard"


# static fields
.field public static bpo:Ljava/lang/String; = "<script type=\"text/javascript\">(function(f){function h(b){b=\'BridgeLog:\'+b;typeof console!=\'undefined\'&&console.log(b);ucapi&&ucapi.debug&&alert(b)}function n(b,a,d){a={errCode:a,ext:d};b.fail&&b.fail.call(this,a)}function i(){return s===e.POLLING?!0:!1}function t(b,a,d,c){if(c)try{c=JSON.parse(decodeURIComponent(c))}catch(f){c=\'\'}var b=i()?l:u,e=b[a];e!==void 0?(d===o.OK?e.success&&e.success.call(this,c):n(e,d,c),delete b[a]):h(\'no callback:\'+a)}function v(){var b=(new Date).valueOf();if(m!==0&&b-m>z)l={},m=0,h(\'polling stop\');else{var a;a:{b=l;for(a in b)if(b.hasOwnProperty(a)){a=!1;break a}a=!0}if(!a){a=\'\';a=k?ucweb.startRequest(p,[w,\'\',\'\',e.POLLING]):f[j][q](w,\'\',\'\',e.POLLING);h(\'pollOnce:\'+a);a:if(a!==\'empty\'){try{a=JSON.parse(a)}catch(d){break a}if(r.call(a)===\'[object Array]\')for(var c in a)if(a.hasOwnProperty(c)){var g=a[c];if(!(g.callbackId===void 0||g.status===void 0||g.result===void 0)){var b=g.callbackId,i=g.status,g=decodeURIComponent(g.result);t(e.POLLING,b,i,g)}}}setTimeout(v,A)}}}var j=\'UCShellJava\',q=\'sdkInvoke\',p=\'shell.jsdk.bridge\',l={},u={},B=Math.floor(Math.random()*1E4),o={OK:0,ACCESS_DENY:1,INVALID_METHOD:2,INVALID_PARAM:3,UNKNOWN_ERROR:4},e={LOAD_URL:0,POLLING:1},k=!0;if(!window.ucweb||!window.ucweb.startRequest)k=!1;var s=e.LOAD_URL;self!=top||window.name==\'uc_smartreader_iframe\'?s=e.POLLING:k=!1;var w=\'__polling_result__\',A=50,m=0,z=6E4;f.ucapi=f.ucapi||{};var r=Object.prototype.toString;if(!f[j]||r.call(f[j][q])!==\'[object Function]\')h(\'UCShellJava.sdkInvoke not exsit\');else if(!k&&i())n(args,o.UNKNOWN_ERROR,\'Not support iframe\');else{f.ucapi.invoke=function(b,a){if(b){var d=b+B++,c={};if(a&&a.success)c.success=a.success,delete a.success;if(a&&a.fail)c.fail=a.fail,delete a.fail;(i()?l:u)[d]=c;c=a=a&&r.call(a)!==\'[object String]\'?JSON.stringify(a):\'\';h(\'invokeNative: \'+b+\':\'+d+\':\'+c);if(k)i()?(ucweb.startRequest(p,[b,c,d,e.POLLING]),m=(new Date).valueOf(),v()):ucweb.startRequest(p,[b,c,d,e.LOAD_URL]);else f[j][q](b,c,d,e.LOAD_URL)}else n(a,o.INVALID_PARAM,\'method is null\')};f[j].sdkCallback=function(b,a,d){h(\'nativeCallback:\'+b+\':\'+a+\':\'+d);t(e.LOAD_URL,b,a,d)};var x=function(){this.listener={}};x.prototype={constructor:this,addEvent:function(b,a){typeof b===\'string\'&&typeof a===\'function\'&&(typeof this.listener[b]===\'undefined\'?this.listener[b]=[a]:typeof this.listener[b][a]!==\'undefined\'&&this.listener[b].push(a));return this},fireEvent:function(b,a){if(b&&this.listener[b]){var d=this.listener[b],c;for(c in d)d.hasOwnProperty(c)&&d[c].call(this,a)}return this},removeEvent:function(b){b&&this.listener[b]&&delete this.listener[b];return this}};var y=new x;f.ucapi.on=function(b,a){y.addEvent(b,a)};f[j].sdkEventFire=function(b,a){h(\'nativeEventFire:\'+b+\':\'+a);if(a)try{a=JSON.parse(a)}catch(d){}y.fireEvent(b,a)}}})(window);</script>"


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method public static zu()Ljava/lang/String;
    .locals 1

    const-string v0, "if (window.UCShellJava &&(!window.ucapi||!window.ucapi.invoke||!window.UCShellJava.sdkCallback)) {\n(function(f){function g(b){ucapi&&ucapi.debug&&alert(\"BridgeLog:\"+b)}function p(b,a,d){a={errCode:a,ext:d};b.fail&&b.fail.call(this,a)}function h(){return t===e.POLLING?!0:!1}function u(b,a,d,c){if(c)try{c=JSON.parse(decodeURIComponent(c))}catch(f){c=\"\"}b=h()?m:v;var e=b[a];void 0!==e?(d===q.OK?e.success&&e.success.call(this,c):p(e,d,c),delete b[a]):g(\"no callback:\"+a)}function w(){var b=(new Date).valueOf();if(0!==n&&6E4<b-n)m={},n=0,g(\"polling stop\");else{var a;a:{b=m;for(a in b)if(b.hasOwnProperty(a)){a=!1;break a}a=!0}if(!a){a=\"\";a=l?ucweb.startRequest(\"shell.jsdk.bridge\",[\"__polling_result__\",\"\",\"\",e.POLLING]):f.UCShellJava.sdkInvoke(\"__polling_result__\",\"\",\"\",e.POLLING);g(\"pollOnce:\"+a);a:if(\"empty\"!==a){try{a=JSON.parse(a)}catch(k){break a}if(\"[object Array]\"===r.call(a))for(var d in a)if(a.hasOwnProperty(d)){var c=a[d];if(void 0!==c.callbackId&&void 0!==c.status&&void 0!==c.result){var b=c.callbackId,h=c.status,c=decodeURIComponent(c.result);u(e.POLLING,b,h,c)}}}setTimeout(w,50)}}}var m={},v={},y=Math.floor(1E4*Math.random()),q={OK:0,ACCESS_DENY:1,INVALID_METHOD:2,INVALID_PARAM:3,UNKNOWN_ERROR:4},e={LOAD_URL:0,POLLING:1},l=!0;window.ucweb&&window.ucweb.startRequest||(l=!1);var t=e.LOAD_URL;self!=top||\"uc_smartreader_iframe\"==window.name?t=e.POLLING:l=!1;var n=0;f.ucapi=f.ucapi||{};var r=Object.prototype.toString,k;k=f.UCShellJava&&\"[object Function]\"===r.call(f.UCShellJava.sdkInvoke)?!0:!1;if(k)if(!l&&h())p(args,q.UNKNOWN_ERROR,\"Not support iframe\");else{f.ucapi.invoke=function(b,a){if(b){var d=\nb+y++,c={};a&&a.success&&(c.success=a.success,delete a.success);a&&a.fail&&(c.fail=a.fail,delete a.fail);(h()?m:v)[d]=c;c=a=a&&\"[object String]\"!==r.call(a)?JSON.stringify(a):\"\";g(\"invokeNative: \"+b+\":\"+d+\":\"+c);l?h()?(ucweb.startRequest(\"shell.jsdk.bridge\",[b,c,d,e.POLLING]),n=(new Date).valueOf(),w()):ucweb.startRequest(\"shell.jsdk.bridge\",[b,c,d,e.LOAD_URL]):f.UCShellJava.sdkInvoke(b,c,d,e.LOAD_URL)}else p(a,q.INVALID_PARAM,\"method is null\")};f.UCShellJava.sdkCallback=function(b,a,d){g(\"nativeCallback:\"+b+\":\"+a+\":\"+d);u(e.LOAD_URL,b,a,d)};k=function(){this.listener={}};k.prototype={constructor:this,addEvent:function(b,a){\"string\"===typeof b&&\"function\"===typeof a&&(\"undefined\"===typeof this.listener[b]?this.listener[b]=[a]:\"undefined\"!==typeof this.listener[b][a]&&this.listener[b].push(a));return this},fireEvent:function(b,a){if(b&&this.listener[b]){var d=this.listener[b],c;for(c in d)d.hasOwnProperty(c)&&d[c].call(this,a)}return this},removeEvent:function(b){b&&this.listener[b]&&delete this.listener[b];return this}};var x=new k;f.ucapi.on=function(b,a){x.addEvent(b,a)};f.UCShellJava.sdkEventFire=function(b,a){g(\"nativeEventFire:\"+b+\":\"+a);if(a)try{a=JSON.parse(a)}catch(d){}x.fireEvent(b,a)}}else g(\"UCShellJava.sdkInvoke not exsit\")})(window);\n}"

    return-object v0
.end method
